DROP DATABASE IF EXISTS burg;
CREATE DATABASE burg;

USE burg

CREATE TABLE bestburger

(

id INT AUTO_INCREMENT NOT NULL,
burgerName VARCHAR (255) NOT NULL,
devoured BOOLEAN NOT NULL DEFAULT 0,
ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
dt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (id)

);