DROP DATABASE IF EXISTS yum;
CREATE DATABASE yum;
USE yum;

CREATE TABLE bur
	
(

id INT AUTO_INCREMENT NOT NULL,
burgerName VARCHAR (255) NOT NULL,
devoured BOOLEAN NOT NULL DEFAULT 0,
ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
dt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (id)

);

