DROP DATABASE IF EXISTS burger_db;
CREATE DATABASE burger_db;

USE burger_db

CREATE TABLE burgers

(

id INT AUTO_INCREMENT NOT NULL,
burgerName VARCHAR (255) NOT NULL,
devoured BOOLEAN NOT NULL DEFAULT 0,
ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
dt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (id)

);

INSERT INTO burgers (burgerName) VALUES ("hawaiianburger");
INSERT INTO burgers (burgerName) VALUES ("pimburger");
INSERT INTO burgers (burgerName) VALUES ("hamburger");
INSERT INTO burgers (burgerName) VALUES ("cheeseburger");

SELECT * FROM burgers